### ISSUE TITLE
Prevent terminal from opening after running

### ISSUE THREAD

**Issue by Raigiku** [nabijaczleweli/BearLibTerminal.rs#10]
Whenever I run a release build of my game, a terminal window opens up. How do I deactivate it? 
My platform is Windows.

**Comment by nabijaczleweli** [comment]
You'll have to add 
```
#![windows_subsystem = "windows"]
```
to your `main.rs` like [this](https://github.com/LoungeCPP/pir-8-emu/blob/e3ebcb8a674d3ff201debd193688b9d477d82e11/src/bin/pir-8-emu.rs#L1).

**Comment by Raigiku** [comment]
Thanks, that solved it!
