### ISSUE TITLE
Link to BearLibTerminal in README broken 

### ISSUE THREAD

**Issue by vmedea** [nabijaczleweli/BearLibTerminal.rs#11]
The link to https://bitbucket.org/cfyzium/bearlibterminal is broken, it looks like the repository disappeared.

I don't know if there is an up-to-date repository by the original author. There's a still somewhat maintained version on github by another author though: https://github.com/tommyettinger/BearLibTerminal

**Comment by nabijaczleweli** [comment]
Good shout! The new canonical location seems to be https://github.com/cfyzium/bearlibterminal, which is consistent with [my mirror](https://github.com/nabijaczleweli/BearLibTerminal); I've repointed the READMEs thereat.

**Comment by vmedea** [comment]
Ah yes, I somehow hadn't noticed the same cfyzium has a repository here, that seems better, thanks.
