### ISSUE TITLE
Alt key unhandled

### ISSUE THREAD

**Issue by mbilker** [nabijaczleweli/BearLibTerminal.rs#5]
BearLibTerminal.rs and BearLibTerminal-sys.rs do not handle BearLibTerminal's Alt key pressed event causing the `EventIterator` to end when the Alt key is pressed.

https://github.com/nabijaczleweli/BearLibTerminal.rs/blob/4464bb5036485c8d5e0be2e2313843ad6e79c611/src/terminal/mod.rs#L439-L444

`TK_ALT` is defined as `0x72` at:

https://github.com/nabijaczleweli/BearLibTerminal/blob/f353dece2c1e3b6ecc31d4d1e2c2b38163cb6fec/Terminal/Include/C/BearLibTerminal.h#L143

**Comment by nabijaczleweli** [comment]
Thanks for catching this! I'll merge https://github.com/mbilker/BearLibTerminal.rs/commit/83bccdb9c3b2c93da189f5c05347a79c5e6c108c if you wanna make a PR :)

**Comment by nabijaczleweli** [comment]
Released in [`v1.4.0`](https://github.com/nabijaczleweli/BearLibTerminal.rs/releases/tag/v1.4.0).

**Comment by gyscos** [comment]
(Note for the future: adding an enum variant is often backward-incompatible, as it breaks exhaustive matching. One solution to that is to disallow exhaustive matching for an enum, for example by adding a hidden, unused variant.)

**Comment by nabijaczleweli** [comment]
Ah, yes, bonne point, that's just one more for the future, I guess. Cheers.
